/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SigninRouteRouteImport } from './routes/signin/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthProfileRouteRouteImport } from './routes/_auth/profile/route'
import { Route as AuthLinksLinkIdRouteImport } from './routes/_auth/links.$linkId'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRouteRoute = SigninRouteRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthProfileRouteRoute = AuthProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLinksLinkIdRoute = AuthLinksLinkIdRouteImport.update({
  id: '/links/$linkId',
  path: '/links/$linkId',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/signin': typeof SigninRouteRoute
  '/about': typeof AboutRoute
  '/profile': typeof AuthProfileRouteRoute
  '/dashboard': typeof AuthDashboardRoute
  '/links/$linkId': typeof AuthLinksLinkIdRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/signin': typeof SigninRouteRoute
  '/about': typeof AboutRoute
  '/profile': typeof AuthProfileRouteRoute
  '/dashboard': typeof AuthDashboardRoute
  '/links/$linkId': typeof AuthLinksLinkIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/signin': typeof SigninRouteRoute
  '/about': typeof AboutRoute
  '/_auth/profile': typeof AuthProfileRouteRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_public/': typeof PublicIndexRoute
  '/_auth/links/$linkId': typeof AuthLinksLinkIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/about'
    | '/profile'
    | '/dashboard'
    | '/links/$linkId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/signin' | '/about' | '/profile' | '/dashboard' | '/links/$linkId'
  id:
    | '__root__'
    | '/_auth'
    | '/_public'
    | '/signin'
    | '/about'
    | '/_auth/profile'
    | '/_auth/dashboard'
    | '/_public/'
    | '/_auth/links/$linkId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  SigninRouteRoute: typeof SigninRouteRoute
  AboutRoute: typeof AboutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/links/$linkId': {
      id: '/_auth/links/$linkId'
      path: '/links/$linkId'
      fullPath: '/links/$linkId'
      preLoaderRoute: typeof AuthLinksLinkIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthProfileRouteRoute: typeof AuthProfileRouteRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthLinksLinkIdRoute: typeof AuthLinksLinkIdRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthProfileRouteRoute: AuthProfileRouteRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthLinksLinkIdRoute: AuthLinksLinkIdRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  SigninRouteRoute: SigninRouteRoute,
  AboutRoute: AboutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
